Repository openshift/cluster-capi-operator, pull requests merged in 2022-05, with the labels that each got.

#52 Add openshift annotations to operator deployment
  hack/assets/customizations.go
  manifests/0000_30_cluster-api_capi-operator_11_deployment.upstream.yaml
Labels: approved, lgtm

#54 Create service account secret manually
  manifests/0000_30_cluster-api_capi-operator_02_service_account.yaml
  pkg/controllers/kubeconfig/kubeconfig.go
  pkg/controllers/kubeconfig/kubeconfig_test.go
Labels: approved, lgtm

#56 Bug 2084545: Create cluster-capi-operator-secret in right namespace
  manifests/0000_30_cluster-api_capi-operator_02_service_account.yaml
Labels: bugzilla/valid-bug, approved, bugzilla/severity-urgent, lgtm

#51 Bug 2086198: [OCPCLOUD-1506] Disable defaulting webhook for cluster objects
  assets/core-capi/core-cluster-api.yaml
  assets/infrastructure-providers/infrastructure-aws.yaml
  assets/infrastructure-providers/infrastructure-azure.yaml
  assets/infrastructure-providers/infrastructure-gcp.yaml
  hack/assets/customizations.go
  hack/assets/providercustomizations.go
Labels: bugzilla/valid-bug, bugzilla/severity-low, approved, lgtm

#57 Bug 2087149: Add watch predicates to kubeconfig controller
  pkg/controllers/kubeconfig/kubeconfig.go
  pkg/controllers/kubeconfig/watch_predicates.go
Labels: bugzilla/severity-medium, bugzilla/valid-bug, approved, lgtm

#59 Bug 2089254: Rotate token secret if its older than 30 minutes
  pkg/controllers/kubeconfig/kubeconfig.go
  pkg/controllers/kubeconfig/kubeconfig_test.go
  pkg/controllers/kubeconfig/suite_test.go
  pkg/test/cleanup.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/k8s.io/client-go/testing/actions.go
  vendor/k8s.io/client-go/testing/fake.go
  vendor/k8s.io/client-go/testing/fixture.go
  vendor/k8s.io/client-go/testing/interface.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-unspecified
