Repository openshift/cluster-capi-operator, pull requests merged in 2023-11, with the labels that each got.

#142 OCPCLOUD-2218: Bump CAPG to v1.5.0
  assets/infrastructure-providers/infrastructure-gcp-provider.yaml
  assets/infrastructure-providers/infrastructure-gcp.yaml
  e2e/go.mod
  e2e/go.sum
  e2e/vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  e2e/vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  e2e/vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  e2e/vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  e2e/vendor/github.com/google/go-cmp/cmp/compare.go
  e2e/vendor/github.com/google/go-cmp/cmp/export.go
  e2e/vendor/github.com/google/go-cmp/cmp/export_panic.go
  e2e/vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  e2e/vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  e2e/vendor/github.com/google/go-cmp/cmp/options.go
  e2e/vendor/github.com/google/go-cmp/cmp/path.go
  e2e/vendor/github.com/google/go-cmp/cmp/report_reflect.go
  e2e/vendor/github.com/onsi/gomega/CHANGELOG.md
  e2e/vendor/github.com/onsi/gomega/gomega_dsl.go
  e2e/vendor/github.com/onsi/gomega/matchers.go
  e2e/vendor/golang.org/x/oauth2/deviceauth.go
  e2e/vendor/golang.org/x/oauth2/oauth2.go
  e2e/vendor/golang.org/x/oauth2/pkce.go
  e2e/vendor/modules.txt
  go.mod
  go.sum
  manifests/0000_30_cluster-api_02_crd.infrastructure-gcp.yaml
  manifests/0000_30_cluster-api_02_providers.configmap.yaml
  providers-list.yaml
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/golang.org/x/oauth2/deviceauth.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#140 OCPBUGS-19841: Add format key into the worker-user-data secret
  pkg/controllers/secretsync/secret_sync_controller.go
  pkg/controllers/secretsync/secret_sync_controller_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#145 OCPBUGS-23467: manifests/0000_30_cluster-api_10_webhooks: Deletion manifest for validating-webhook-configuration
  manifests/0000_30_cluster-api_10_webhooks.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#135 OCPBUGS-19842: Limit deletion webhook to openshift namespace
  pkg/webhook/cluster.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#148 OCPBUGS-24301: openstack: Don't substitute manager container command
  pkg/controllers/capiinstaller/component_customizer.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
