Repository openshift/cluster-capi-operator, pull requests merged in 2023-10, with the labels that each got.

#133 Update OWNERS
  OWNERS
Labels: approved, lgtm

#141 OCPBUGS-22403: Disable CAPI Azure Infrastructure Provider
  manifests/0000_30_cluster-api_02_providers.configmap.yaml
  providers-list.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#136 [release-4.14] OCPBUGS-22314: fix: add missing azure identity diff
  assets/infrastructure-providers/infrastructure-azure.yaml
  manifests/0000_30_cluster-api_02_crd.infrastructure-azure.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
