Repository openshift/cluster-capi-operator, pull requests merged in 2024-07, with the labels that each got.

#184 OCPBUGS-36369: Revert cluster-api-operator go.sum hash
  go.sum
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#186 OCPCLOUD-2638: Add stricter linting configuration
  .golangci.yml
  cmd/cluster-capi-operator/main.go
  pkg/controllers/capiinstaller/capi_installer_controller.go
  pkg/controllers/capiinstaller/capi_installer_controller_test.go
  pkg/controllers/capiinstaller/component_customizer.go
  pkg/controllers/capiinstaller/suite_test.go
  pkg/controllers/capiinstaller/watch_predicates.go
  pkg/controllers/cluster/core.go
  pkg/controllers/cluster/core_test.go
  pkg/controllers/cluster/suite_test.go
  pkg/controllers/common_consts.go
  pkg/controllers/infracluster/infracluster_controller.go
  pkg/controllers/infracluster/infracluster_controller_test.go
  pkg/controllers/infracluster/suite_test.go
  pkg/controllers/infracluster/watch_predicates.go
  pkg/controllers/kubeconfig/generate.go
  pkg/controllers/kubeconfig/generate_test.go
  pkg/controllers/kubeconfig/kubeconfig.go
  pkg/controllers/kubeconfig/kubeconfig_test.go
  pkg/controllers/kubeconfig/suite_test.go
  pkg/controllers/kubeconfig/watch_predicates.go
  pkg/controllers/secretsync/secret_sync_controller.go
  pkg/controllers/secretsync/secret_sync_controller_test.go
  pkg/controllers/secretsync/suite_test.go
  pkg/controllers/secretsync/watch_predicates.go
  pkg/controllers/unsupported/suite_test.go
  pkg/controllers/unsupported/unsupported_controller.go
  pkg/controllers/unsupported/unsupported_controller_test.go
  pkg/controllers/unsupported/watch_predicates.go
  pkg/operatorstatus/operator_status.go
  pkg/test/cleanup.go
  pkg/test/crdbuilder.go
  pkg/test/envtest.go
  pkg/util/duration.go
  pkg/util/patch.go
  pkg/util/platform.go
  pkg/util/readconfig.go
  pkg/util/slice.go
  pkg/webhook/cluster.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#183 OCPBUGS-36296: fix: sort CredentialsRequest manifests after namespace
  manifests/0000_30_cluster-api_01_credentials-request.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only
