Repository openshift/cluster-capi-operator, pull requests merged in 2024-10, with the labels that each got.

#209 METAL-966: manifests-gen: process ConfigMaps
  manifests-gen/customizations.go
Labels: approved, lgtm, jira/valid-reference

#208 OCPCLOUD-2750: Add fuzz conversion testing for MAPI2CAPI conversions
  go.mod
  go.sum
  pkg/conversion/capi2mapi/aws.go
  pkg/conversion/capi2mapi/machine.go
  pkg/conversion/capi2mapi/machineset.go
  pkg/conversion/mapi2capi/aws.go
  pkg/conversion/mapi2capi/aws_fuzz_test.go
  pkg/conversion/mapi2capi/aws_test.go
  pkg/conversion/mapi2capi/machine.go
  pkg/conversion/mapi2capi/machineset.go
  pkg/conversion/mapi2capi/suite_test.go
  pkg/conversion/test/fuzz.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/matchers.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#213 OCPCLOUD-2707: Clarify why DeviceIndex is always zero
  pkg/conversion/capi2mapi/aws.go
  pkg/conversion/mapi2capi/aws.go
Labels: approved, lgtm, jira/valid-reference

#214 OCPCLOUD-2750: Add CAPI2MAPI Machine(Set) fuzz testing
  pkg/conversion/capi2mapi/aws.go
  pkg/conversion/capi2mapi/aws_fuzz_test.go
  pkg/conversion/capi2mapi/suite_test.go
  pkg/conversion/mapi2capi/aws.go
  pkg/conversion/mapi2capi/aws_fuzz_test.go
  pkg/conversion/mapi2capi/machine.go
  pkg/conversion/test/fuzz.go
Labels: approved, lgtm, jira/valid-reference

#189 OCPCLOUD-2206: Generate AzureCluster resource for CAPI cluster
  e2e/azure_test.go
  pkg/controllers/infracluster/azure.go
  pkg/controllers/infracluster/infracluster_controller.go
Labels: approved, lgtm, jira/valid-reference

#212 OCPCLOUD-2643: MachineSyncReconciler - split reconciles
  pkg/controllers/machinesync/machine_sync_controller.go
  pkg/controllers/machinesync/suite_test.go
  pkg/test/crdbuilder.go
  pkg/test/envtest.go
Labels: approved, lgtm, jira/valid-reference

#217 OCPCLOUD-2643: MachineSetSync controller bootstrap
  cmd/machine-api-migration/main.go
  pkg/controllers/machinesetsync/machineset_sync_controller.go
  pkg/controllers/machinesetsync/machineset_sync_controller_test.go
  pkg/controllers/machinesetsync/suite_test.go
  pkg/controllers/machinesync/machine_sync_controller.go
  pkg/util/watch_filters.go
Labels: approved, lgtm, jira/valid-reference

#219 OCPCLOUD-2643: Machinesetsync split reconcile
  pkg/controllers/machinesetsync/machineset_sync_controller.go
  pkg/controllers/machinesetsync/suite_test.go
  pkg/controllers/machinesync/machine_sync_controller.go
  pkg/test/crdbuilder.go
  pkg/test/envtest.go
Labels: approved, lgtm, jira/valid-reference

#220 OCPBUGS-42490: fix: azure: do not deploy CAPI on AzureStackCloud
  cmd/cluster-capi-operator/main.go
Labels: approved, qe-approved, lgtm, jira/valid-bug, jira/valid-reference

#222 OCPCLOUD-2749: capi2mapi conversion pkg negative testing
  go.mod
  go.sum
  pkg/conversion/capi2mapi/aws.go
  pkg/conversion/capi2mapi/aws_test.go
  pkg/conversion/capi2mapi/machine.go
  pkg/conversion/capi2mapi/machine_test.go
  pkg/conversion/capi2mapi/machineset_test.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/cluster-api/core/v1beta1/cluster.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/cluster-api/core/v1beta1/machine.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/cluster-api/core/v1beta1/machineset.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awscluster.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awsmachine.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/cluster-api/infrastructure/v1beta2/awsmachinetemplate.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#223 NO-JIRA: Update OWNERS
  OWNERS
Labels: approved, lgtm, jira/valid-reference

#224 OCPCLOUD-2749: mapi2capi conversion pkg negative testing: add missing machine/machineset tests
  go.mod
  go.sum
  pkg/conversion/mapi2capi/machine.go
  pkg/conversion/mapi2capi/machine_test.go
  pkg/conversion/mapi2capi/machineset_test.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/machine.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/machineset.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#225 NO-JIRA: updated spell and comment
  pkg/conversion/mapi2capi/aws.go
Labels: approved, lgtm, jira/valid-reference

#227 OCPBUGS-43971: bump CAPO to v0.11.0
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1beta1/conditions_consts.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1beta1/doc.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1beta1/groupversion_info.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1beta1/identity_types.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1beta1/openstackcluster_types.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1beta1/openstackclustertemplate_types.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1beta1/openstackmachine_types.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1beta1/openstackmachinetemplate_types.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1beta1/types.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1beta1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/utils/optional/conversion.go
  vendor/sigs.k8s.io/cluster-api-provider-openstack/pkg/utils/optional/types.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#228 OCPCLOUD-2642: manifests-gen: Allow overriding kustomize component path
  manifests-gen/README.md
  manifests-gen/main.go
  manifests-gen/providers.go
Labels: approved, lgtm, jira/valid-reference
