Repository openshift/cluster-capi-operator, pull requests merged in 2025-05, with the labels that each got.

#289 OCPBUGS-55947: Should not use v1beta1 of the AdmissionRegistration API group
  manifests-gen/customizations.go
  pkg/controllers/capiinstaller/capi_installer_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#290 OCPBUGS-55985: fix: machine: propagate non-authoritative deletion
  pkg/controllers/machinesync/machine_sync_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#286 OCPCLOUD-2943: MachineSet deletion logic
  pkg/controllers/machinesetsync/machineset_sync_controller.go
  pkg/controllers/machinesetsync/machineset_sync_controller_test.go
  pkg/controllers/machinesync/machine_sync_controller.go
Labels: approved, lgtm, jira/valid-reference

#301 OCPBUGS-56709: fix: bump openshift/library-go to fix ValidatingAdmissionPolicyV1 apply in capiinstaller
  go.mod
  go.sum
  pkg/test/envtest.go
  vendor/github.com/openshift/api/.golangci.yaml
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/apiserver/v1/types_apirequestcount.go
  vendor/github.com/openshift/api/cloudnetwork/v1/generated.proto
  vendor/github.com/openshift/api/cloudnetwork/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1alpha1/types_cluster_image_policy.go
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/helm/v1beta1/types_helm_chart_repository.go
  vendor/github.com/openshift/api/machine/v1/types_alibabaprovider.go
  vendor/github.com/openshift/api/machine/v1/types_controlplanemachineset.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/types_powervsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_awsprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_vsphereprovider.go
  vendor/github.com/openshift/api/monitoring/v1/types.go
  vendor/github.com/openshift/api/networkoperator/v1/generated.proto
  vendor/github.com/openshift/api/networkoperator/v1/types_egressrouter.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_machineconfiguration.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_console_01_consoles.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_csi-driver_01_clustercsidrivers-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_csi-driver_01_clustercsidrivers-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_csi-driver_01_clustercsidrivers-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_50_csi-driver_01_clustercsidrivers-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_etcdbackup.go
  vendor/github.com/openshift/api/sharedresource/v1alpha1/types_shared_configmap.go
  vendor/github.com/openshift/api/sharedresource/v1alpha1/types_shared_secret.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/networking.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/networking.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
