Repository openshift/cluster-capi-operator, pull requests merged in 2025-03, with the labels that each got.

#256 OCPCLOUD-2792: corecluster: set controller level conditions + tests
  pkg/controllers/capiinstaller/capi_installer_controller.go
  pkg/controllers/clusteroperator/clusteroperator_controller.go
  pkg/controllers/corecluster/corecluster_controller.go
  pkg/controllers/corecluster/corecluster_controller_test.go
  pkg/controllers/infracluster/infracluster_controller.go
  pkg/controllers/secretsync/secret_sync_controller.go
  pkg/operatorstatus/operator_status.go
Labels: approved, lgtm, jira/valid-reference

#260 OCPCLOUD-2718: Add default VolumeSize for MAPI to CAPI conversion
  pkg/conversion/mapi2capi/aws.go
  pkg/conversion/mapi2capi/aws_fuzz_test.go
  pkg/conversion/mapi2capi/aws_test.go
Labels: approved, lgtm, jira/valid-reference

#269 NO-JIRA: Update TODOs with new Jira issues
  pkg/conversion/capi2mapi/machine.go
  pkg/conversion/mapi2capi/machine.go
  pkg/conversion/test/fuzz/fuzz.go
Labels: approved, lgtm, jira/valid-reference

#266 OCPBUGS-53057: Fix misspelled CAPI IBMPowerVSCluster kind name in corecluster generation logic
  pkg/controllers/corecluster/corecluster_controller.go
Labels: approved, ok-to-test, lgtm, jira/valid-bug, jira/valid-reference

#273 TRT-2048: Revert "OCPCLOUD-2792: corecluster: set controller level conditions + tests"
  pkg/controllers/capiinstaller/capi_installer_controller.go
  pkg/controllers/clusteroperator/clusteroperator_controller.go
  pkg/controllers/corecluster/corecluster_controller.go
  pkg/controllers/corecluster/corecluster_controller_test.go
  pkg/controllers/infracluster/infracluster_controller.go
  pkg/controllers/secretsync/secret_sync_controller.go
  pkg/operatorstatus/operator_status.go
Labels: approved, lgtm, jira/valid-reference

#276 NO-JIRA: fix: e2e: azure conditionally set identity
  e2e/azure_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#277 NO-JIRA: Update version variable in generate-ocp-manifests hook script
  hack/rebasebot-hook-scripts/generate-ocp-manifests.sh
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#265 OCPCLOUD-2647: CAPI to MAPI Machine Synchronisation
  pkg/controllers/machinesync/machine_sync_controller.go
  pkg/controllers/machinesync/machine_sync_controller_test.go
  pkg/conversion/mapi2capi/aws.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only
