Repository openshift/cluster-capi-operator, pull requests merged in 2025-01, with the labels that each got.

#235 OCPCLOUD-2642: Reference ASO image for installation
  manifests/image-references
Labels: approved, lgtm, jira/valid-reference

#248 OCPBUGS-29815: fix: always update clusteroperator status versions when differing
  pkg/controllers/corecluster/corecluster_controller_test.go
  pkg/controllers/unsupported/suite_test.go
  pkg/controllers/unsupported/unsupported_controller_test.go
  pkg/operatorstatus/operator_status.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference, acknowledge-critical-fixes-only

#249 [release-4.18] OCPBUGS-48429: fix: always update clusteroperator status versions when differing
  Makefile
  pkg/controllers/cluster/core_test.go
  pkg/controllers/cluster/suite_test.go
  pkg/controllers/unsupported/suite_test.go
  pkg/controllers/unsupported/unsupported_controller_test.go
  pkg/operatorstatus/operator_status.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#250 [release-4.17] OCPBUGS-48493: fix: always update clusteroperator status versions when differing
  Makefile
  pkg/controllers/cluster/core_test.go
  pkg/controllers/cluster/suite_test.go
  pkg/controllers/unsupported/suite_test.go
  pkg/controllers/unsupported/unsupported_controller_test.go
  pkg/operatorstatus/operator_status.go
Labels: approved, qe-approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#216 MULTIARCH-5043: Add Powervs support for CAPI-MAPI conversion
  pkg/controllers/machinesetsync/machineset_sync_controller.go
  pkg/controllers/machinesync/machine_sync_controller.go
  pkg/conversion/capi2mapi/aws.go
  pkg/conversion/capi2mapi/machine.go
  pkg/conversion/capi2mapi/powervs.go
  pkg/conversion/capi2mapi/powervs_fuzz_test.go
  pkg/conversion/capi2mapi/powervs_test.go
  pkg/conversion/mapi2capi/aws.go
  pkg/conversion/mapi2capi/machine.go
  pkg/conversion/mapi2capi/powervs.go
  pkg/conversion/mapi2capi/powervs_fuzz_test.go
  pkg/conversion/mapi2capi/powervs_test.go
  pkg/conversion/mapi2capi/util.go
  pkg/conversion/test/fuzz/fuzz.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/aws_failure_domains.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/azure_failure_domains.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/control_plane_machine_set.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/gcp_failure_domains.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/nutanix_failure_domains.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/nutanix_provider_spec.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/openshift_machine_v1beta1_template.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/openstack_failure_domains.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/powervs_provider_spec.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/vsphere_failure_domains.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#253 [release-4.16] OCPBUGS-49603: fix: always update clusteroperator status versions when differing
  Makefile
  go.mod
  go.sum
  pkg/controllers/cluster/core_test.go
  pkg/controllers/cluster/infra_test.go
  pkg/controllers/cluster/suite_test.go
  pkg/controllers/kubeconfig/generate_test.go
  pkg/controllers/kubeconfig/kubeconfig_test.go
  pkg/controllers/kubeconfig/suite_test.go
  pkg/controllers/secretsync/secret_sync_controller_test.go
  pkg/controllers/unsupported/suite_test.go
  pkg/controllers/unsupported/unsupported_controller_test.go
  pkg/operatorstatus/operator_status.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/.gitignore
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/LICENSE
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/Makefile
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/cleanup.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/conditions.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/logger.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/config/v1/cluster_operator.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/config/v1/infrastructure.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/core/v1/configmap.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/core/v1/namespace.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/core/v1/node.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/core/v1/secret.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/core/v1/service.go
  vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/tools.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/komega/OWNERS
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/komega/default.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/komega/equalobject.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/komega/interfaces.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/komega/komega.go
Labels: approved, qe-approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#254 OCPCLOUD-2792: Repurpose unsupported controller to a broader clusteroperator one
  cmd/cluster-capi-operator/main.go
  pkg/controllers/clusteroperator/clusteroperator_controller.go
  pkg/controllers/clusteroperator/clusteroperator_controller_test.go
  pkg/controllers/clusteroperator/suite_test.go
  pkg/controllers/clusteroperator/watch_predicates.go
  pkg/controllers/corecluster/corecluster_controller.go
  pkg/controllers/corecluster/corecluster_controller_test.go
  pkg/controllers/unsupported/unsupported_controller_test.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only
