Repository openshift/cluster-capi-operator, pull requests merged in 2025-06, with the labels that each got.

#308 [release-4.18] OCPBUGS-56919: fix: bump openshift/library-go to fix ValidatingAdmissionPolicyV1 apply in capiinstaller
  cmd/machine-api-migration/main.go
  go.mod
  go.sum
  pkg/controllers/capiinstaller/capi_installer_controller.go
  pkg/controllers/machinesetsync/suite_test.go
  pkg/controllers/machinesync/suite_test.go
  vendor/github.com/openshift/api/config/v1/types_node.go
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_nodes-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_nodes-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_nodes-DevPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_nodes-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/features/util.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/cluster-control-plane-machine-set-operator/LICENSE
  vendor/github.com/openshift/cluster-control-plane-machine-set-operator/pkg/util/feature_gate.go
  vendor/github.com/openshift/cluster-control-plane-machine-set-operator/pkg/util/infrastructure.go
  vendor/github.com/openshift/cluster-control-plane-machine-set-operator/pkg/util/leaderelection.go
  vendor/github.com/openshift/cluster-control-plane-machine-set-operator/pkg/util/pointer.go
  vendor/github.com/openshift/cluster-control-plane-machine-set-operator/pkg/util/tls.go
  vendor/github.com/openshift/cluster-control-plane-machine-set-operator/pkg/util/watch_filters.go
  vendor/github.com/openshift/library-go/pkg/apiserver/jsonpatch/jsonpatch.go
  vendor/github.com/openshift/library-go/pkg/config/clusterstatus/clusterstatus.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_in_memory.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_logging.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_upstream.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/canonicalize.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.proto
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/generated.proto
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1/apiservice.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#295 OCPBUGS-54705: mapi2capi: Create new machine template when changing MAPI providerSpec
  e2e/aws_test.go
  e2e/framework/machineset.go
  pkg/controllers/common_consts.go
  pkg/controllers/machinesetsync/machineset_sync_controller.go
  pkg/controllers/machinesetsync/machineset_sync_controller_test.go
  pkg/controllers/machinesync/machine_sync_controller_test.go
  pkg/conversion/mapi2capi/aws.go
  pkg/conversion/mapi2capi/powervs.go
  pkg/conversion/test/fuzz/fuzz.go
  pkg/util/hash.go
  pkg/util/watch_filters.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#324 NO-JIRA: Remove manifest for validating-webhook-configuration
  manifests/0000_30_cluster-api_10_webhooks.yaml
Labels: approved, ok-to-test, lgtm, jira/valid-reference
