Repository openshift/cluster-capi-operator, pull requests merged in 2025-08, with the labels that each got.

#320 OCPCLOUD-2992: migration e2e for creating machine with authoritativeAPI ClusterAPI
  e2e/framework/machine.go
  e2e/machine_migration_test.go
Labels: approved, lgtm, jira/valid-reference

#318 OCPCLOUD-2992: e2e test for mapimachine creation
  e2e/e2e_test.go
  e2e/mapimachines_test.go
Labels: approved, tide/merge-method-squash, lgtm, jira/valid-reference

#347 OCPCLOUD-2871: Machine conversion for the delete-machine annotation and unit tests
  pkg/conversion/capi2mapi/common.go
  pkg/conversion/capi2mapi/machine_test.go
  pkg/conversion/mapi2capi/machine_test.go
  pkg/conversion/mapi2capi/util.go
  pkg/util/annotations.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only, verified
